<?php 
define("MYSQL_HOST","localhost");
define("MYSQL_USER","root");
define("MYSQL_PWD","123");
define("MYSQL_DB","hck2");
define("MYSQL_CHARSET","GBK");
define("TABLE_PRE","koufu_");
define("DOMAIN","");
define("SKINS","default");
define("BINDUC",0);
?>